<a href="https://colab.research.google.com/github/ritikverma7373-hue/Introduction-in-python-IIT-Madras-lecture-/blob/python-language/Lecture_48.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix multiplication
At the end of this lecture, student will be understand the mathmatical idea behind matrix multiplication

In [4]:
r1=[1,2,3]
r2=[4,5,6]
r3=[7,8,9]

s1=[1,2,1]
s2=[6,2,3]
s3=[4,2,1]

A=[]
B=[]
A.append(r1)
A.append(r2)
A.append(r3)

B.append(s1)
B.append(s2)
B.append(s3)

C=[[0,0,0],[0,0,0],[0,0,0]]
dim=3
# C[i][j] is the dot product of the ith row of A and the jth coloumn of B.
for i in range(dim):
  for j in range(dim):
     for k in range(dim):
       C[i][j]=C[i][j]+A[i][k]*B[k][j]
print(C)

[[25, 12, 10], [58, 30, 25], [91, 48, 40]]


In [21]:
import numpy
A=[[1,2,3],[4,5,6],[7,8,9]]
B=[[1,2,1],[6,2,3],[4,2,1]]
#x=numpy.dot(A,B)
#print(x)
x=numpy.asmatrix(A)
y=numpy.asmatrix(B)
print(x*y)

[[25 12 10]
 [58 30 25]
 [91 48 40]]
